services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: golang-roadmap:unstable
    container_name: golang-roadmap-app
    platform: 'linux/amd64'
    command: sh -c "build/local/start-container.sh"
    ports:
      - '${APP_PORT:-8081}:80'
    volumes:
      - ./:/app